apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.65.10
  selector:
    app: ftps
  ports:
  - name: ftps1
    port: 20
    protocol: TCP
    targetPort: 20
  - name: ftps2
    port: 21
    protocol: TCP
    targetPort: 21
  - port: 30020
    name: ftpsside1
    protocol: TCP
    targetPort: 30020
  - port: 30021
    name: ftpsside2
    protocol: TCP
    targetPort: 30021
