apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: wordpress
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.65.10
  selector:
    app: wordpress
  ports:
  - name: https
    port: 5050
    protocol: TCP
    targetPort: 5050
